### ISSUE TITLE
[Bug] `TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'` when running `write_tfrecord_species.py`

### ISSUE THREAD

**Issue by jolespin** [Gaius-Augustus/Tiberius#6]
I'd like to train a model on some genomes I have available locally.  I have my gene models in GFF format so I converted to GTF with `gffread`, extracted the longest isoform, then tried creating `tfrecords` but the script failed. 

I'm attaching the input files in case it's useful:

```
$ python Tiberius/bin/write_tfrecord_species.py --fasta ${SPECIES}.fa --gtf ${SPECIES}.longest.gtf --out tfrecords/${SPECIES}
2024-10-07 21:43:22.216480: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/efs/sandbox/sandbox/development/jolespin/Testing/EukGeneModeling/tiberius_testing/Tiberius/bin/write_tfrecord_species.py", line 371, in <module>
    main()
  File "/home/ec2-user/SageMaker/efs/sandbox/sandbox/development/jolespin/Testing/EukGeneModeling/tiberius_testing/Tiberius/bin/write_tfrecord_species.py", line 309, in main
    fasta, ref = get_species_data_hmm(genome_path=args.fasta, annot_path=args.gtf, 
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/SageMaker/efs/sandbox/sandbox/development/jolespin/Testing/EukGeneModeling/tiberius_testing/Tiberius/bin/write_tfrecord_species.py", line 119, in get_species_data_hmm
    f_chunk = fasta.get_flat_chunks(strand='+', pad=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/SageMaker/efs/sandbox/sandbox/development/jolespin/Testing/EukGeneModeling/tiberius_testing/Tiberius/bin/genome_fasta.py", line 143, in get_flat_chunks
    // (self.chunksize - self.overlap) + 1
        ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```
[pt_mag.tar.gz](https://github.com/user-attachments/files/17284856/pt_mag.tar.gz)

**Comment by LarsGab** [comment]
Hi, 

thanks for using Tiberius!

The script requires you have to use the `--wsize` argument to specify the sequence size of each training example. For example, we used `--wsize 99999` for the training with the mammalian genomes.

I seem to have forgotten to include it in the documentation, I'm sorry. 

Best, 
Lars

**Comment by jolespin** [comment]
Do you recommend a good parameter choice that I can use for diatoms?

**Comment by KatharinaHoff** [comment]
Please send me an email (or give me a phone call). I am willing to share
results on this, possibly collaborate, but the current results are not so
great that I want to publish a parameter set, yet.

Josh L. Espinoza ***@***.***> schrieb am Mi. 9. Okt. 2024 um
18:18:

**Comment by jolespin** [comment]
@LarsGab does v1.1.4 solve this issue? I'm still interested in training a model.

**Comment by LarsGab** [comment]
Hi,

the latest commit (not released yet) and the latest Singularity image (singularity build tiberius.sif docker://larsgabriel23/tiberius:latest) should ressolve this issue. 

Best,
Lars

**Comment by jolespin** [comment]
Excellent! I'd like to train this on a collection of fungal and protist genomes once it's ready.  Perhaps in July? I plan to develop VEBA 3.0 around that time and would like to replace MetaEuk with Tiberius in that build.

**Comment by KatharinaHoff** [comment]
I am very happy that you have this plan. We already have the diatoms
parameters that you can use, and we also are highly interested in other
protists. Someone in our group is also developing a BRAKER-based pipeline
for recovery of eukaryotic bins, but using Tiberius is obviously faster and
may have accuracy advantages (remains to be seen... how well it works in
other protists and fungi, the big challenge with the protists is the
training data).

**Comment by jolespin** [comment]
For metagenomics, I would err on the side of accessibility over reducing false positives just because the methods available are so few and far between.  MetaEuk and Miniprot are the only tools I know that can be used for "gene prediction" in metagenomics for eukaryotic organisms.  MetaEuk is extremely resource intensive and Miniprot I just haven't gotten it to work with my MicroEuk database.  I'd rather just move away from the protein alignment based method and train protist/fungi models.  Maybe the ones in BUSCO with a classification prior head?

**Comment by KatharinaHoff** [comment]
We used miniprot but the output needs filtering, and you still miss a lot.

Josh L. Espinoza ***@***.***> schrieb am Fr. 11. Apr. 2025 um
20:30:
